#!/bin/bash

#install visual studio code, sublimetext and pycharm

# install visual studio code
# taken from https://code.visualstudio.com/docs/setup/linux
cd "$(mktemp -d)"
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg

apt-get -y install apt-transport-https
apt-get -y update
apt-get -y install code # or code-insiders

# install sublimetext
# taken from https://www.sublimetext.com/docs/linux_repositories.html
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo apt-get -y install apt-transport-https
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get -y update
sudo apt-get -y install sublime-text

# install pycharm
# taken from https://linuxconfig.org/how-to-install-pycharm-on-ubuntu-20-04-linux-desktop
if [ "$(dpkg --print-architecture)" = "arm64" ]; then
	wget --quiet https://download-cdn.jetbrains.com/python/pycharm-community-2023.3.3-aarch64.tar.gz
else
	wget --quiet https://download-cdn.jetbrains.com/python/pycharm-community-2023.3.3.tar.gz
fi
sudo tar xzf pycharm-*.tar.gz --one-top-level=pycharm --strip-components=1 -C /opt/
sudo ln -s /opt/pycharm/bin/pycharm.sh /usr/bin/pycharm