#!/usr/bin/env bash
set -eo pipefail  # Better error handling and exiting on error

SCRIPTS_PATH=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
PROJECT_PATH=$(realpath "$SCRIPTS_PATH/..")
ROOT_PATH=$(realpath "$PROJECT_PATH/..")

source "$SCRIPTS_PATH/utils.sh"

IMAGE_NAME="robotour.simg"
IMAGE_PATH="${PROJECT_PATH}/images/${IMAGE_NAME}"

ENV_VARIABLES=(
    ROS_MASTER_URI
    ROS_HOSTNAME
    ROS_IP
    ROS_HOME
    ROS_LOG_DIR
    ROSCONSOLE_CONFIG_FILE
    ROS_PYTHON_LOG_CONFIG_FILE
    HOSTNAME
    DISPLAY
    USER
    XAUTHORITY
    LANG
    DBUS_SESSION_BUS_ADDRESS
)

update_repository() {
    if is_online; then
        echo "Updating repository"
        (cd "$PROJECT_PATH" && git pull)
    fi
}

# If you have NVidia GPU and rendering acceleration doesn't work for you, call `export ARO_SINGULARITY_NV=1` before
# launching this script. However, this only works on Ubuntu 20.04 and older systems.
set_nvidia_gpu() {
    nv=""
    if [ "$ARO_SINGULARITY_NV" = "1" ]; then
        echo "Setting up NVidia GPU support."
        nv="--nv"
    fi
}

bind_directories() {
    bind="${ROOT_PATH}:${ROOT_PATH}"
    if [ -d /snap ]; then
      echo "Mounting /snap directory."
      bind="${bind},/snap:/snap"
    fi
}

main() {
    # Accept argument -u or --update to update the image
    if [ "${1:-}" = "-u" ] || [ "${1:-}" = "--update" ]; then
      echo "Updating the image."
      is_online && "$SCRIPTS_PATH"/download_singularity_image
    fi

    # If in singularity container exit
    in_singularity && echo "You are already inside a singularity container." && exit 1

    # Check whether singularity is installed and install it if not
    "${SCRIPTS_PATH}"/install_singularity

    update_repository

    bind_directories
    set_nvidia_gpu

    export PS1="\[\033[01;32m\]\u@\h\[\033[00m\]\[\e[33m\] [RoboTour] \[\e[0m\]:\[\033[01;34m\]\w\[\033[00m\]$ "

    for var_name in "${ENV_VARIABLES[@]}"; do
        export_environment_variable_if_present "$var_name"
    done

    echo "Starting Singularity container from image ${IMAGE_PATH}."
    singularity exec -e -B "${ROOT_PATH}" "${IMAGE_PATH}" "${SCRIPTS_PATH}/initialize_workspace" "$@"
}

# Execute main function
main "$@"
