#!/usr/bin/env bash
set -euo pipefail  # Better error handling and exiting on error

SCRIPTS_PATH=$(realpath "$(dirname "${BASH_SOURCE[0]}")")

main() {
    local ws_parent="${ws_parent:-$(pwd)}"
    local rosdep="${rosdep:-n}"

    if [ -z "${ws_parent}" ]; then
        read -p "Using ${ws_parent} as a parent directory for catkin workspaces, are you sure? [Y/n] " -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit
        fi
    fi
    mkdir -p "${ws_parent}"

    echo "=================================================================="
    echo "Setting up catkin workspaces in the selected directory:"
    echo "  ${ws_parent}/robolab"
    echo "  ${ws_parent}/aro"
    echo "  ${ws_parent}/lar"
    echo "=================================================================="

    # Setup Catkin workspaces
    "${SCRIPTS_PATH}/setup_catkin_workspace" \
        --extend "/opt/ros/noetic" \
        --ros "noetic" \
        --rosdep "$rosdep" \
        --rosinstall "${SCRIPTS_PATH}/../config/robolab_noetic.rosinstall" \
        --install "${ws_parent}/robolab" \
        "$(mktemp -d)"

    "${SCRIPTS_PATH}/setup_catkin_workspace" \
        --extend "${ws_parent}/robolab" \
        --ros "noetic" \
        --rosdep "$rosdep" \
        --rosinstall "${SCRIPTS_PATH}/../config/robolab_aro_noetic.rosinstall student-packages/dependencies.rosinstall" \
        --install "${ws_parent}/aro" \
        "$(mktemp -d)"

    "${SCRIPTS_PATH}/setup_catkin_workspace" \
        --extend "${ws_parent}/robolab" \
        --ros "noetic" \
        --rosdep "$rosdep" \
        --rosinstall "${SCRIPTS_PATH}/../config/robolab_lar_noetic.rosinstall" \
        --install "${ws_parent}/lar" \
        "$(mktemp -d)"

    apt-get clean
}

main
